set -g default-terminal "screen-256color"

# Disable stupid horrible escape delay
set -sg escape-time 0

# set bases to 1
set -g base-index 1
set -g pane-base-index 1

# enable activity alerts
setw -g monitor-activity on
set -g visual-activity on

set -g history-limit 10000

set -g mouse on

# sane splits
bind-key \ split-window -h -c '#{pane_current_path}'
bind-key - split-window -v -c '#{pane_current_path}'

# better prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# meta-arrow keys for pane switching
bind -n M-Left select-pane -L
bind -n M-Down select-pane -D
bind -n M-Up select-pane -U
bind -n M-Right select-pane -R

# shift arrows for windows switching
bind -n S-Left previous-window
bind -n S-Right next-window

set -ga terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "xterm-256color"
set -g status-style 'bg=#1E272C,fg=#6A7D89'
set -g window-status-current-style 'fg=cyan'
set -g mode-style 'bg=cyan,fg=black'
set -g message-style 'bg=black,fg=cyan'
set -g pane-border-style 'bg=black,fg=#1E272C'
set -g pane-active-border-style 'bg=black,fg=#1E272C'

# window status
setw -g window-status-format " #F#I: #W#F "
setw -g window-status-current-format " #F#I: #W#F "
setw -g window-status-format " #I  #W "
setw -g window-status-current-format " #I  #W "
setw -g window-status-attr reverse

# Info on left (I don't have a session display for now)
set -g status-left ''

set -g status-position bottom
set -g status-attr dim
set -g status-left ''
set -g status-right '#[bold] %d/%m #[bold] %H:%M:%S '
set -g status-right-length 50
set -g status-left-length 20

setw -g window-status-current-attr bold
setw -g window-status-current-format ' #I:#W#F '

setw -g window-status-attr none
setw -g window-status-format ' #I#W#F '

setw -g window-status-bell-attr bold
