[font]
size = 12
normal = { style = "Regular", family = "JetBrainsMono Nerd Font" }

[keyboard]
bindings = [{ key = "Enter", mods = "Command", action = "ToggleFullscreen" }]

[[hints.enabled]]
binding = { key = "U", mods = "Control|Shift" }
command = "open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Control"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
