gui:
  expandFocusedSidePanel: true
  showRandomTip: false
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - yellow
      - bold

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
